language: node_js
sudo: false
node_js:
        - "11.10.1"
env:
  - PATH=$HOME/purescript:$PATH
install:
  - cp psc-package-dev.json psc-package.json
  - npm install -g bower pulp psc-package
  - npm install
  - psc-package build
script:
  - travis_wait pulp --psc-package test

cache:
  directories:
    - output
