language: node_js
sudo: false
node_js:
        - "11.10.1"
env:
  - PATH=$HOME/purescript:$PATH
install:
  - npm install -g bower pulp
  - npm install
  - bower install
  - npm build
script:
  - travis_wait pulp test

cache:
  directories:
    - output
