language: node_js
sudo: false
node_js:
        - "6.11.3"
env:
  - PATH=$HOME/purescript:$PATH
install:
  - npm install -g bower pulp
  - npm install
  - bower install
script:
  - travis_wait pulp test

cache:
  directories:
    - output
